#!/usr/bin/env python
from glob import glob
import os
import numpy as np
try:
    from astropy.io import fits as pf
except:
    import pyfits as pf
import matplotlib.pyplot as plt
from tqdm import tqdm
import argparse
import getpass
#from ircs import utils

#config = utils.check_config()
data_dir = '.'#config[1]

parser = argparse.ArgumentParser(description=
    'Sorts the .fits files into proper directories based on their header',
    usage='use "%(prog)s --help" for more information',
    formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('--save_list',
                help='outputs text file of list per category',
                type=bool, default=True)
args = parser.parse_args()
save_list = args.save_list

if not os.path.exists(data_dir):
    os.makedirs(input_dir)
    print('Created: {}'.format(data_dir))

#main
utils.image_sorter(data_dir, save_list)

print('\n-----------------------')
print('         DONE')
print('-----------------------\n')
